version: '2'

services:
  web:
    container_name: laravel-web
    image: shomatan/nginx:1.13.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    restart: always

  app:
    container_name: laravel-app
    image: shomatan/laravel:5.4-php-7.1
    environment:
      LARAVEL_DB_HOST: db
    volumes:
      - ./laravel:/var/www/html
    restart: always

  db:
    container_name: laravel-db
    image: mariadb:10.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER:     laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    restart: always